FROM alpine:3

LABEL author="Rafy Maulana Ichsan Hidayat"
LABEL company="kopi rumah mantan" website="https://www.kopirumahmantan.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"